---
# tasks file for nginx_proxy
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy Nginx proxy configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/proxy

- name: Enable proxy site
  file:
    src: /etc/nginx/sites-available/proxy
    dest: /etc/nginx/sites-enabled/proxy
    state: link
    force: yes

- name: Disable default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: true

