---
# tasks file for nginx_send
- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Deploy index page
  template:
    src: index.j2
    dest: /var/www/html/index.html

- name: Ensure nginx is running
  service:
    name: nginx
    state: started
    enabled: true
